# Generated by Django 4.2.3 on 2023-07-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session_years',
            new_name='Session_Year',
        ),
    ]
