# Generated by Django 4.2.3 on 2023-07-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_staff_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_leave',
            old_name='data',
            new_name='date',
        ),
    ]
