# Generated by Django 4.2.3 on 2023-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_data_staff_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_leave',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
