# Generated by Django 4.2.3 on 2023-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_attendance_attendance_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_report',
            old_name='attendance',
            new_name='attendance_id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
