# Generated by Django 4.2.3 on 2023-08-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_attendance_attendance_report_attendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
