# Generated by Django 4.2.3 on 2023-08-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_subject_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_notification',
            name='status',
        ),
    ]
